---
title: "Analyse du Système de Mesures"
author: "NOUAL R., SOTTAS A., VIALLANEIX L."
date: '2022-04-16'
output: 
  html_document: 
    fig_width: 10
    fig_height: 15
---

## Analyse du systeme de mesure
### Introduction

* Ce document est une préparation pour acceuillir les données du projets capteur granulométrique.
* Les calculs sont réalisé à l'aide du package SixSigma.
* Les données ont été prise à partir de ce document :  
[démarche iso 17025](http://www.demarcheiso17025.com/fiche005.html#d2)  
Cet étape à pour but de se familiariser avec la fonction ss.rr() de SixSigma qui permet d'implémenter la méthode R&R (Réptabilité et Reproductibilité).
Cet outils statistique permet de quantifier la performance d'un système de mesure en déterminant la contribution de la répétabilité, de la reproductibilité du sytème et celle de la variance de la variable d'intérêt du système de mesure par rapport à la variance totale de la mesure.
* Cette analyse nous donnera la capabilité du système.

### Méthodologie

La méthode décrite par la littérature demande les éléments suivants : 

* 2 à 3 opérateurs.  
* 10 pièces de test (les capteurs granulométriques dans notre cas).  
* 3 séries de mesure par capteur et par opérateur (soit un total de 90 mesures).  


### Variable d'intérêt

* La variable mesurée est la sensibilité du capteur granulométrique (ou R/R0).

### Le code


```{r}
# Import SixSigma package
library(SixSigma)

# Specify the factors for appraisals - Opérateurs dans notre cas
operateurs <- factor(rep(1:3, each = 30))

# Specify the factors for parts - les 10 capteurs de test
sensor <- factor(rep(rep(1:10, each = 3), 3))

# Specify the factors for replicates
run <- factor(rep(1:3, 30))
 
# Specify the measured variable
sensibilite <- c(45.08,45.1,45.09,44.94,44.97,44.93,45.08,45.11,45.13,44.97,45.02,45.01,44.92,44.95,45.01,45.03,45.06,45.05,45.24,45.36,45.31,45.16,45.16,45.1,45.2,45.2,45.24,45.07,45.1,45.05,45.01,45.04,45.02,44.92,44.95,44.95,44.95,45.11,45.11,45.01,44.93,45,44.95,44.99,44.97,45.04,45.06,44.99,45.12,45.21,45.32,45.12,45.13,45.13,45.06,45.19,45.24,45.02,45.05,45.09,45.04,45.07,45.07,44.92,44.97,44.91,45.1,45.12,45.11,45.02,44.99,44.99,44.99,44.97,44.95,45.07,45.03,45.02,45.26,45.29,45.28,45.13,45.13,45.14,45.19,45.17,45.16,45.1,45.1,45.09)

# Build data frame msa (measurement systeme analyse)
msa <- data.frame(operateurs, sensor, run, sensibilite)
#Aperçu du début et de la fin du dataframe
head(msa)
tail(msa)

# Perform Gage R&R Analysis 
my.rr <- ss.rr(var = sensibilite,
               part = sensor,
               appr = operateurs,
               data = msa,
               sigma = 5.15,
               alphaLim = 2,
               main = "Six Sigma Gage R&R Measure",
               sub = "Granulometric Sensors Project MSA")

# RESULTATS

```

### Discussions et conclusions

* **Reproductibilité**
* **Répétabilité**
* **Variabilité capteur**
* **Capabilité**

### Références

* www.demarcheiso17025.com
* Six Sigma with R, Statistical Engineering for Process Improvement, Emilio L.Cano, Javier M. Moguerza, Andrés Redchuck
* [Wiki](https://fr.wikipedia.org/wiki/Gage_R%26R)



Fin du document


